<a href="https://colab.research.google.com/github/dacasfilipe/Python_data_science/blob/main/Mysql_livraria_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
-- MySQL Workbench Synchronization
-- Generated: 2023-08-20 21:50
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Filipe Da Cas

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `livraria_data_science`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;
sql="""CREATE TABLE teste1.aluno(
  id_aluno int not null auto_increment primary key,
  nome varchar(60),
  sexo varchar(1)
)"""
ok - CREATE TABLE IF NOT EXISTS `livraria_data_science`.`autores` (
  `id_autores` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id_autores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ok - CREATE TABLE IF NOT EXISTS `livraria_data_science`.`livros` (
  `id_livros` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  `ano_publicacao` INT(11) NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT NULL,
  `fk_id_categoria` INT(11) NOT NULL,
  PRIMARY KEY (`id_livros`),
  INDEX `livro_categoria_idx` (`fk_id_categoria` ASC) VISIBLE,
  CONSTRAINT `livro_categoria`
    FOREIGN KEY (`fk_id_categoria`)
    REFERENCES `livraria_data_science`.`categorias` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ok - CREATE TABLE IF NOT EXISTS `livraria_data_science`.`categorias` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ok - CREATE TABLE IF NOT EXISTS `livraria_data_science`.`clientes` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ok - CREATE TABLE IF NOT EXISTS `livraria_data_science`.`vendas` (
  `id_venda` INT(11) NOT NULL AUTO_INCREMENT,
  `data_venda` DATE NULL DEFAULT NULL,
  `valor_total` DECIMAL(10,2) NULL DEFAULT NULL,
  `fk_id_cliente` INT(11) NOT NULL,
  `clientes_id_cliente` INT(11) NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_vendas_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `livraria_data_science`.`clientes` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ok - CREATE TABLE IF NOT EXISTS `livraria_data_science`.`itens_venda` (
  `id_item` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_id_livros` INT(11) NOT NULL,
  `fk_id_venda` INT(11) NOT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `valor_item` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_item`, `fk_id_livros`, `fk_id_venda`),
  INDEX `fk_livros_has_vendas_vendas1_idx` (`fk_id_venda` ASC) VISIBLE,
  INDEX `fk_livros_has_vendas_livros_idx` (`fk_id_livros` ASC) VISIBLE,
  CONSTRAINT `fk_livros_has_vendas_livros`
    FOREIGN KEY (`fk_id_livros`)
    REFERENCES `livraria_data_science`.`livros` (`id_livros`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_livros_has_vendas_vendas1`
    FOREIGN KEY (`fk_id_venda`)
    REFERENCES `livraria_data_science`.`vendas` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ok - CREATE TABLE IF NOT EXISTS `livraria_data_science`.`livro_autor` (
  `fk_id_livros` INT(11) NOT NULL,
  `fk_id_autores` INT(11) NOT NULL,
  PRIMARY KEY (`fk_id_livros`, `fk_id_autores`),
  INDEX `fk_autores_has_livros_livros1_idx` (`fk_id_livros` ASC) VISIBLE,
  INDEX `fk_autores_has_livros_autores1_idx` (`fk_id_autores` ASC) VISIBLE,
  CONSTRAINT `fk_autores_has_livros_autores1`
    FOREIGN KEY (`fk_id_autores`)
    REFERENCES `livraria_data_science`.`autores` (`id_autores`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_autores_has_livros_livros1`
    FOREIGN KEY (`fk_id_livros`)
    REFERENCES `livraria_data_science`.`livros` (`id_livros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;